import { createInterface } from "node:readline";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execFileSync } from "node:child_process";
import { AGENT_NAMES, type AgentName } from "../core/config.js";

const CONFIG_DIR = join(homedir(), ".gnhf");
const CONFIG_PATH = join(CONFIG_DIR, "config.yml");

const AGENT_DESCRIPTIONS: Record<AgentName, string> = {
  claude: "Anthropic's Claude Code CLI — best for general-purpose coding tasks",
  codex: "OpenAI's Codex CLI — strong at code generation and completion",
  rovodev: "Atlassian Rovo Dev — integrated with Atlassian tools",
  opencode: "OpenCode — open-source, multi-provider coding agent",
  copilot: "GitHub Copilot CLI — GitHub-integrated coding assistant",
};

const AGENT_BINARIES: Record<AgentName, string> = {
  claude: "claude",
  codex: "codex",
  rovodev: "acli",
  opencode: "opencode",
  copilot: "copilot",
};

function prompt(
  rl: ReturnType<typeof createInterface>,
  question: string,
): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

function isBinaryOnPath(binary: string): boolean {
  try {
    const cmd = process.platform === "win32" ? "where" : "which";
    execFileSync(cmd, [binary], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

export async function runInit(): Promise<void> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    console.log("");
    console.log("  Welcome to gnhf setup!");
    console.log("  ======================");
    console.log("");

    // Step 1: Check existing config
    if (existsSync(CONFIG_PATH)) {
      console.log(`  Found existing config at ${CONFIG_PATH}`);
      const overwrite = await prompt(
        rl,
        "  Overwrite it? (y/N): ",
      );
      if (overwrite.toLowerCase() !== "y") {
        console.log("  Keeping existing config. You're all set!");
        console.log("");
        return;
      }
      console.log("");
    }

    // Step 2: Choose agent
    console.log("  Which agent would you like to use by default?");
    console.log("");
    for (let i = 0; i < AGENT_NAMES.length; i++) {
      const name = AGENT_NAMES[i];
      console.log(`    ${i + 1}. ${name} — ${AGENT_DESCRIPTIONS[name]}`);
    }
    console.log("");

    let agent: AgentName = "claude";
    const agentChoice = await prompt(
      rl,
      `  Enter number (1-${AGENT_NAMES.length}) [1]: `,
    );
    if (agentChoice) {
      const idx = parseInt(agentChoice, 10) - 1;
      if (idx >= 0 && idx < AGENT_NAMES.length) {
        agent = AGENT_NAMES[idx];
      } else {
        console.log("  Invalid choice, defaulting to claude.");
      }
    }
    console.log(`  Selected: ${agent}`);
    console.log("");

    // Step 3: Validate binary
    const binary = AGENT_BINARIES[agent];
    const found = isBinaryOnPath(binary);
    let agentPathOverride = "";

    if (found) {
      console.log(`  Found "${binary}" on your PATH.`);
    } else {
      console.log(`  Warning: "${binary}" was not found on your PATH.`);
      console.log(`  gnhf needs "${binary}" to be available to run the ${agent} agent.`);
    }
    console.log("");

    // Step 4: Optional path override
    const customPath = await prompt(
      rl,
      `  Custom path to ${agent} binary? (leave blank to skip): `,
    );
    if (customPath) {
      agentPathOverride = customPath;
      console.log(`  Will use: ${agentPathOverride}`);
      console.log("");
    }

    // Step 5: Max consecutive failures
    const maxFailInput = await prompt(
      rl,
      "  Max consecutive failures before aborting [3]: ",
    );
    const maxConsecutiveFailures = maxFailInput
      ? parseInt(maxFailInput, 10) || 3
      : 3;

    // Step 6: Sleep prevention
    const sleepInput = await prompt(
      rl,
      "  Prevent system sleep during runs? (Y/n): ",
    );
    const preventSleep = sleepInput.toLowerCase() !== "n";

    // Step 7: Write config
    const lines: string[] = [
      "# gnhf configuration",
      "# Generated by gnhf init",
      "",
      "# Agent to use by default",
      `agent: ${agent}`,
      "",
    ];

    if (agentPathOverride) {
      lines.push("# Custom agent binary path");
      lines.push("agentPathOverride:");
      lines.push(`  ${agent}: ${agentPathOverride}`);
      lines.push("");
    }

    lines.push("# Abort after this many consecutive failures");
    lines.push(`maxConsecutiveFailures: ${maxConsecutiveFailures}`);
    lines.push("");
    lines.push("# Prevent the machine from sleeping during a run");
    lines.push(`preventSleep: ${preventSleep}`);
    lines.push("");

    mkdirSync(CONFIG_DIR, { recursive: true });
    writeFileSync(CONFIG_PATH, lines.join("\n"), "utf-8");

    // Step 8: Success message
    console.log("");
    console.log("  You're all set!");
    console.log("  ===============");
    console.log("");
    console.log(`  Config written to: ${CONFIG_PATH}`);
    console.log("");
    console.log("  Next steps:");
    console.log("    1. cd into a git repository");
    console.log('    2. Run: gnhf "your objective here"');
    console.log("    3. Go to sleep and wake up to a branch full of work!");
    console.log("");
    console.log("  Useful commands:");
    console.log("    gnhf stats           — view usage statistics");
    console.log('    gnhf --help          — see all options"');
    console.log("    gnhf --worktree      — run in a separate worktree");
    console.log("");
  } finally {
    rl.close();
  }
}
